device:
    gpu: 3
    
dataset:
    name: naufalso/carla_hd
    cache_dir: manhole_data
    batch_size: 8
    
manhole_set:
    manhole_candidate_path: manhole_data
    image_size: 256
    adversarial_sample_images:
        normal: adversarial_example/naive_manhole.jpg
        artistic: adversarial_example/artistic_manhole.jpg
        full: adversarial_example/full_manhole.png
        mde: adversarial_example/mde_manhole.png
        ss: adversarial_example/ss_manhole.png
        ss_ta: adversarial_example/ss_ta_manhole.png
        additional: adversarial_example/texture_epoch_24.png
    
model:
    mde_model: mono_640x192
    ss_model: ddrnet_23
    
patches:
    texture:
        texture_resolution: 256
        texture_augmentation:
            brightness: 0.2
            contrast: 0.1
        output_augmentation:
            brightness: 0.2
            contrast: 0.1
    loss_init_weight:
        mde_loss_weight: 2.0
        ss_ua_loss_weight: 0.5
        ss_ta_loss_weight: 0.5
        tv_loss_weight: 1.0
        content_loss_weight: 0.5
        background_loss_weight: 0.0
        
parameter:
    epochs: 25
    learning_rate: 0.01

log:
    log_name: test
    log_prediction: 5
    
evaluation:
    patch_path: log/